apiVersion: monitoring.rhobs/v1
kind: ServiceMonitor
metadata:
  name: go-api
  namespace: observability-demo
  labels:
    monitoring.rhobs/stack: observability-stack
    app.kubernetes.io/name: go-api
    app.kubernetes.io/component: backend
spec:
  selector:
    matchLabels:
      app: go-api
  endpoints:
    - port: http
      path: /metrics
      interval: 30s
      scheme: http
