apiVersion: monitoring.rhobs/v1
kind: ServiceMonitor
metadata:
  name: node-app
  namespace: observability-demo
  labels:
    monitoring.rhobs/stack: observability-stack
    app.kubernetes.io/name: node-app
    app.kubernetes.io/component: frontend
spec:
  selector:
    matchLabels:
      app: node-app
  endpoints:
    - port: http
      path: /metrics
      interval: 30s
      scheme: http
