quarkus.http.port=${PORT:4003}
quarkus.http.cors=true
quarkus.http.cors.origins=*
quarkus.http.cors.headers=accept,authorization,content-type,x-requested-with
quarkus.http.cors.methods=GET,POST,OPTIONS

# Logging
quarkus.log.console.enable=true
quarkus.log.console.level=INFO
quarkus.log.category."com.github.cldmnky.lolcat".level=DEBUG

# Prometheus metrics
quarkus.micrometer.export.prometheus.enabled=true
quarkus.micrometer.export.prometheus.path=/metrics

