---
apiVersion: v1
kind: Secret
metadata:
  name: tempostack-dev-minio
  namespace: openshift-tempo-operator
type: Opaque
stringData:
  bucket: "borg-tempo"
  endpoint: "https://storage.blahonga.me:9199"
  access_key_id: "MWGlKcndcwhg35J9H3jF"
  access_key_secret: "MWGlKcndcwhg35J9H3jF"
